In [1]:
import gym
import torch
from Policy import Policy

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
env = gym.make('CartPole-v0')
print(env.__dict__)
print(env.action_space)

{'env': <gym.envs.classic_control.cartpole.CartPoleEnv object at 0x0000022A2554B408>, 'action_space': Discrete(2), 'observation_space': Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32), 'reward_range': (-inf, inf), 'metadata': {'render.modes': ['human', 'rgb_array'], 'video.frames_per_second': 50}, '_max_episode_steps': 200, '_elapsed_steps': None}
Discrete(2)


In [4]:
print(env.reset())
print(env.step(0))

[-0.01574439  0.01325762  0.02378525  0.00359592]
(array([-0.01547924, -0.18219723,  0.02385717,  0.30368747]), 1.0, False, {})


In [5]:
for i in range(10):
    print(env.action_space.sample())

1
0
0
1
0
1
1
0
1
1


In [6]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

Episode finished after 13 timesteps
Episode finished after 43 timesteps
Episode finished after 29 timesteps
Episode finished after 22 timesteps
Episode finished after 43 timesteps
Episode finished after 11 timesteps
Episode finished after 17 timesteps
Episode finished after 24 timesteps
Episode finished after 19 timesteps
Episode finished after 23 timesteps
Episode finished after 14 timesteps
Episode finished after 24 timesteps
Episode finished after 24 timesteps
Episode finished after 14 timesteps
Episode finished after 14 timesteps
Episode finished after 22 timesteps
Episode finished after 35 timesteps
Episode finished after 16 timesteps
Episode finished after 31 timesteps
Episode finished after 15 timesteps


In [7]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
#         env.render()
        action = 0 if observation[2] < 0 else 1
        observation, reward, done, info = env.step(action)
#         print("observation:", observation)
#         print("reward:", reward)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

Episode finished after 32 timesteps
Episode finished after 51 timesteps
Episode finished after 40 timesteps
Episode finished after 52 timesteps
Episode finished after 53 timesteps
Episode finished after 40 timesteps
Episode finished after 31 timesteps
Episode finished after 25 timesteps
Episode finished after 45 timesteps
Episode finished after 32 timesteps
Episode finished after 56 timesteps
Episode finished after 57 timesteps
Episode finished after 42 timesteps
Episode finished after 40 timesteps
Episode finished after 42 timesteps
Episode finished after 41 timesteps
Episode finished after 44 timesteps
Episode finished after 67 timesteps
Episode finished after 35 timesteps
Episode finished after 56 timesteps


In [8]:
print(env.observation_space.__dict__)

{'dtype': dtype('float32'), 'shape': (4,), 'low': array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32), 'high': array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32), 'bounded_below': array([ True,  True,  True,  True]), 'bounded_above': array([ True,  True,  True,  True]), '_np_random': None}


In [17]:
x = torch.tensor([env.reset()], dtype=torch.float32)
x = x.to(device)

In [18]:
model = Policy().to(device)

In [19]:
model(x)

tensor([[-0.0425,  0.0330]], device='cuda:0', grad_fn=<AddmmBackward>)

In [20]:
torch.max(model(x), 0)[1].item()

ValueError: only one element tensors can be converted to Python scalars

In [24]:
import torch.nn as nn
l = nn.CrossEntropyLoss()
print(l(model(x), torch.tensor([1]).to(device)))

tensor(0.6561, device='cuda:0', grad_fn=<NllLossBackward>)
